### ISSUE TITLE
C(R)UD Issue

### ISSUE THREAD

**Issue by alexchirea** [richie87/codeigniter-meets-extjs#9]
Hi,
When I try to create/update/delete an item I get the following error: 
**_"Unknown error: The server did not send any information about the error."_**

**Comment by richie87** [comment]
Sorry, but still need help?

**Comment by alexchirea** [comment]
Nope, but thanks anyway :-)

Alexandru Chirea
E-mail: alexchirea11@gmail.com
Telefon: 0721 525 088

2016-10-04 21:38 GMT+03:00 Richard Jaeger notifications@github.com:
